image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass rsync

deploy_production:
  only:
    refs:
      - develop
  stage: deploy
  script:
    - yarn install
    - yarn build
    - cd build/
    - ls
