import tw from 'twin.macro'

export default {
    bgColor: {
        blueberry: tw`bg-blueberry`,
        eggplant: tw`bg-eggplant`,
        steel: tw`bg-steel`,
    },
    maxWidth: {
        sm: tw`max-w-sm`,
        lg: tw`max-w-lg`,
        md: tw`max-w-md`,
        xl: tw`max-w-xl`,
        xl2: tw`max-w-2xl`,
        xl3: tw`max-w-3xl`,
        xl4: tw`max-w-4xl`,
        xl5: tw`max-w-5xl`,
        xl6: tw`max-w-6xl`,
        xl7: tw`max-w-7xl`,
        full: tw`max-w-full`,
        max: tw`max-w-max`,
    },
    width: {
        w10: tw`w-10`,
        w12: tw`w-12`,
        w16: tw`w-16`,
        w20: tw`w-20`,
        w24: tw`w-24`,
        w28: tw`w-28`,
        w32: tw`w-32`,
        w36: tw`w-36`,
        w40: tw`w-40`,
        w48: tw`w-48`,
        w52: tw`w-52`,
        w60: tw`w-60`,
        w64: tw`w-64`,
        w72: tw`w-72`,
        w80: tw`w-80`,
        w96: tw`w-96`,
        w1012: tw`w-10/12`,
        w212: tw`w-2/12`,
        full: tw`w-full`,
    },
    marginLeft: {
        ml48: tw`ml-48`,
    },
    padding: {
        pl0: tw`pl-0`,
        pl1: tw`pl-1`,
    },
}
